/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-04-27 06:47:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Preference;
import model.User;
import model.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/src/navbar.jsp", Long.valueOf(1430117268000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
//  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
  //  _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("  <title>Profile</title>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"lib/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"lib/css/navbar.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"lib/css/profile.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"lib/js/jquery-1.11.2.min.js\"> </script>\r\n");
      out.write("  <script src=\"lib/js/bootstrap.js\"> </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Make any changes to the nav bar here! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Creating the Nav Bar -->\r\n");
      out.write("  \t<div class= \"navbar navbar-fixed-top navbar-inverse\">\r\n");
      out.write("\t  \t<div class=\"container\">\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t<a href=\"#\" class=\"pull-left navbar-brand\"><img width=\"90px\" height=\"22px\" src=\"/Housing/lib/images/houSCingWhite.png\"></a>  \t\r\n");
      out.write("\t  \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"search\">\r\n");
      out.write("\t\t        <a href=\"/Housing/search\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-search\">\r\n");
      out.write("\t\t          </i> Search\r\n");
      out.write("\t\t        </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"home\">\r\n");
      out.write("\t\t        <a href=\"/Housing/src/mapPage.jsp\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-map-marker\">\r\n");
      out.write("\t\t          </i> Map\r\n");
      out.write("\t\t        </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if(session.getAttribute("curr") != null){
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"chatButtonOnNavbar\">\r\n");
      out.write("\t\t          <a href=\"/Housing/src/chat.jsp\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-flag\"> </i> Chat\r\n");
      out.write("\t\t          </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"chatButtonOnNavbar\">\r\n");
      out.write("\t\t          <a href=\"/Housing/src/friends.jsp\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-heart\"> </i> Friends\r\n");
      out.write("\t\t          </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t<p class=\"navbar-text\">Welcome, ");
      out.print( ((User)(session.getAttribute("curr"))).getFirstName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("          \t\t\t<i class=\"glyphicon glyphicon-user\"></i> <span class=\"caret\"></span></a>\r\n");
      out.write("          \t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("            \t\t\t<li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/profile\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-user\">\r\n");
      out.write("\t\t          \t\t\t</i> My Profile\r\n");
      out.write("\t\t       \t\t\t \t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("\t\t      \t\t\t<li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/top-housing\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-map-marker\">\r\n");
      out.write("\t\t          \t\t\t</i> Top Housing\r\n");
      out.write("\t\t       \t\t\t \t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("\t\t\t            <li class=\"divider\"></li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t            \t<a href=\"/Housing/logout\">\r\n");
      out.write("\t\t\t            \t<i class=\"glyphicon glyphicon-off\">\r\n");
      out.write("\t\t          \t\t\t</i> Logout\r\n");
      out.write("\t\t\t            \t</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("          \t\t\t</ul>   \r\n");
      out.write("          \t\t</li>   \t\t\t\r\n");
      out.write("          \t</ul>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t ");
} else {
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("          \t\t\t<i class=\"glyphicon glyphicon-user\"></i> <span class=\"caret\"></span></a>\r\n");
      out.write("          \t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("            \t\t\t<li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/login\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-user\">\r\n");
      out.write("\t\t          \t\t\t</i> Login\r\n");
      out.write("\t\t        \t\t\t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("\t\t\t            <li class=\"divider\"></li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/signup\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-circle-arrow-up\">\r\n");
      out.write("\t\t          \t\t\t</i> Sign Up\r\n");
      out.write("\t\t        \t\t\t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("          \t\t\t</ul>   \r\n");
      out.write("          \t\t</li>   \t\t\t\r\n");
      out.write("          \t</ul>\r\n");
      out.write("          \r\n");
      out.write("         ");
} 
      out.write("   \r\n");
      out.write("\t\t \r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- Finished creating the Nav Bar -->\r\n");
      out.write("\r\n");
 
//setting the type for the alert box
String alertType = null;
String alertPhrase = null;
if(request.getAttribute("success") != null && (Boolean)request.getAttribute("success") == true){
	alertType = "alert-success";
	alertPhrase = "Success!";
} else if (request.getAttribute("success") != null && (Boolean)request.getAttribute("success") == false) {
	alertType = "alert-danger";
	alertPhrase = "Error!";
}

      out.write("\r\n");
      out.write("\r\n");
 if(alertType != null){ 
      out.write("\r\n");
      out.write("<div class=\"alert ");
      out.print( alertType );
      out.write(" alert-dismissable fade in\">\r\n");
      out.write("    <span class=\"close\" data-dismiss=\"alert\">&times;</span>\r\n");
      out.write("    <strong>");
      out.print( alertPhrase );
      out.write("</strong> ");
      out.print( request.getAttribute("message") );
      out.write("\r\n");
      out.write("</div>\r\n");
 request.setAttribute("success", null); 
      out.write('\r');
      out.write('\n');
 request.setAttribute("message", null); 
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\r\n");

User curr = (User)session.getAttribute("curr"); 
Preference currPrefs = curr.getPrefs();

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- multistep form -->\r\n");
      out.write("<form id=\"msform\" action=\"/Housing/profile\" method=\"post\">\r\n");
      out.write("\t<!-- progressbar -->\r\n");
      out.write("\t<ul id=\"progressbar\">\r\n");
      out.write("\t\t<li class=\"active\">Living Style</li>\r\n");
      out.write("\t\t<li>Study Habits</li>\r\n");
      out.write("\t\t<li>Personal Secrets</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<!-- fieldsets -->\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<h2 class=\"fs-title\">Living Style</h2>\r\n");
      out.write("\t\t<!--  <h3 class=\"fs-subtitle\">What I Want</h3 -->\t\t\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"text-left\">\r\n");
      out.write("\t\t<span>What type of room do you prefer?</span>\r\n");
      out.write("\t\t<div class = \"form-group\"></div>\r\n");
      out.write("\t\t<select class=\"form-control\" name=\"room-type\">\r\n");
      out.write("\t    \t<option value=\"single\"\r\n");
      out.write("\t\t    ");
 if(currPrefs.getRoomType() != null && ((String)currPrefs.getRoomType()).equals("single")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Single</option>\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t<option value=\"double\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getRoomType() != null && ((String)currPrefs.getRoomType()).equals("double")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Double</option>\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t<option value=\"triple\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getRoomType() != null && ((String)currPrefs.getRoomType()).equals("triple")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Triple</option> \t\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br/>\t\t\r\n");
      out.write("\t\t<span>How often do you cook?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"cook-frequency\" min=\"0\" max=\"10\" value=");
      out.print( "" + currPrefs.getCookFrequency() );
      out.write(" />\r\n");
      out.write("\t\t<span>How clean and tidy are you?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"clean-frequency\" min=\"0\" max=\"10\" value=");
      out.print( "" + currPrefs.getCleanliness() );
      out.write(" />\r\n");
      out.write("\t\t<span>How often are you out late/party?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"party-frequency\" min=\"0\" max=\"10\" value=");
      out.print( "" + currPrefs.getPartyFrequency() );
      out.write(" />\r\n");
      out.write("\t\t<span>How often do you have guests over?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"guest-frequency\" min=\"0\" max=\"10\" value=");
      out.print( "" + currPrefs.getGuestFrequency() );
      out.write(" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"button\" name=\"next\" class=\"next action-button\" value=\"Next\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<h2 class=\"fs-title\">Study Habits</h2>\r\n");
      out.write("\t<!-- \t<h3 class=\"fs-subtitle\">Things I Do</h3> -->\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"text-left\">\r\n");
      out.write("\t\t<span>What is your grade level?</span>\r\n");
      out.write("\t\t<div class = \"form-group\"></div>\r\n");
      out.write("\t\t<select class=\"form-control\" name=\"school-year\">\r\n");
      out.write("\t    \t<option value=\"freshman\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getSchoolYear() != null && ((String)currPrefs.getSchoolYear()).equals("freshman")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Freshman</option>\r\n");
      out.write("\t    \t<option value=\"sophomore\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getSchoolYear() != null && ((String)currPrefs.getSchoolYear()).equals("sophomore")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Sophomore</option>\r\n");
      out.write("\t    \t<option value=\"junior\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getSchoolYear() != null && ((String)currPrefs.getSchoolYear()).equals("junior")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Junior</option>\r\n");
      out.write("\t    \t<option value=\"senior\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getSchoolYear() != null && ((String)currPrefs.getSchoolYear()).equals("senior")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Senior</option>\r\n");
      out.write("\t    \t<option value=\"graduate\"\r\n");
      out.write("\t    \t");
 if(currPrefs.getSchoolYear() != null && ((String)currPrefs.getSchoolYear()).equals("graduate")){ 
      out.write("\r\n");
      out.write("\t\t\t\tselected=\"selected\"\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t    \t>Graduate</option>\r\n");
      out.write("\t\t</select>\t\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<span>What time do you sleep?</span>\r\n");
      out.write("\t\t<input type=\"time\" class=\"time\" name=\"sleep-time\" value=");
      out.print( currPrefs.getSleepingTime() );
      out.write(" />\t\t\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<span>What time do you wake up?</span>\r\n");
      out.write("\t\t<input type=\"time\" class=\"time\" name=\"wake-time\" value=");
      out.print( currPrefs.getWakingTime() );
      out.write(" />\t\t\r\n");
      out.write("\t\t<br/>\t\t\r\n");
      out.write("\t\t<span>How often do you plan on studying in the room?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"study-frequency\" min=\"0\" max=\"10\" value=");
      out.print( "" + currPrefs.getStudyFrequency() );
      out.write(" />\r\n");
      out.write("\t\t<span>How loud would you like music playing?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"music-loudness\" min=\"0\" max=\"10\" value=");
      out.print( "" + currPrefs.getMusicLoudness() );
      out.write(" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"button\" name=\"previous\" class=\"previous action-button\" value=\"Previous\" />\r\n");
      out.write("\t\t<input type=\"button\" name=\"next\" class=\"next action-button\" value=\"Next\" />\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<h2 class=\"fs-title\">Personal Secrets</h2>\r\n");
      out.write("\t<!-- \t<h3 class=\"fs-subtitle\">This is Me</h3>-->\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"checkbox-container\">\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t<label class=\"checkbox-label\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" value=\"smokes\" name=\"smokes\"\r\n");
      out.write("\t\t\t\t\t");
 if((Boolean)currPrefs.getSmokes()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\tchecked\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t/> I smoke\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t<label class=\"checkbox-label\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" value=\"greek\" name=\"greek\"\r\n");
      out.write("\t\t\t\t\t");
 if((Boolean)currPrefs.getGreek()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\tchecked\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t/> I am Greek\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t\t<label class=\"checkbox-label\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" class=\"checkbox\" value=\"pets\" name=\"pets\"\r\n");
      out.write("\t\t\t\t\t");
 if((Boolean)currPrefs.getPets()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\tchecked\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t/> I have pets\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<div class=\"text-left\">\r\n");
      out.write("\t\t<span>How willing are you to share your belongings?</span>\r\n");
      out.write("\t\t<input type=\"range\" class=\"form-group\" name=\"privacy\" min=\"0\" max=\"10\" value=");
      out.print( currPrefs.getPrivacy() );
      out.write(" />\r\n");
      out.write("\t\t<textarea name=\"hobbies\" placeholder=\"I enjoy/I am a part of...\">");
      out.print( currPrefs.getHobbies() );
      out.write("</textarea>\r\n");
      out.write("\t\t<textarea name=\"fun-fact\" placeholder=\"Something fun about me is that I...\">");
      out.print( currPrefs.getFunFact() );
      out.write("</textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"button\" name=\"previous\" class=\"previous action-button\" value=\"Previous\" />\r\n");
      out.write("\t\t<input type=\"submit\" class=\"action-button\" value=\"Save\" />\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://thecodeplayer.com/uploads/js/jquery-1.9.1.min.js\" type=\"text/javascript\"></script> \r\n");
      out.write("<!-- jQuery easing plugin --> \r\n");
      out.write("<script src=\"http://thecodeplayer.com/uploads/js/jquery.easing.min.js\" type=\"text/javascript\"></script> \r\n");
      out.write("<script src=\"lib/js/profile.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
