/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-05-18 04:13:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import model.Preference;
import model.User;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/src/navbar.jsp", Long.valueOf(1430117268000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("model.Preference");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("  <title>Search</title>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"lib/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"lib/css/navbar.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"lib/css/housing.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"lib/js/jquery-1.11.2.min.js\"> </script>\r\n");
      out.write("  <script src=\"lib/js/bootstrap.js\"> </script>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Make any changes to the nav bar here! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Creating the Nav Bar -->\r\n");
      out.write("  \t<div class= \"navbar navbar-fixed-top navbar-inverse\">\r\n");
      out.write("\t  \t<div class=\"container\">\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t<a href=\"#\" class=\"pull-left navbar-brand\"><img width=\"90px\" height=\"22px\" src=\"/Housing/lib/images/houSCingWhite.png\"></a>  \t\r\n");
      out.write("\t  \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"search\">\r\n");
      out.write("\t\t        <a href=\"/Housing/search\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-search\">\r\n");
      out.write("\t\t          </i> Search\r\n");
      out.write("\t\t        </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"home\">\r\n");
      out.write("\t\t        <a href=\"/Housing/src/mapPage.jsp\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-map-marker\">\r\n");
      out.write("\t\t          </i> Map\r\n");
      out.write("\t\t        </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if(session.getAttribute("curr") != null){
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"chatButtonOnNavbar\">\r\n");
      out.write("\t\t          <a href=\"/Housing/src/chat.jsp\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-flag\"> </i> Chat\r\n");
      out.write("\t\t          </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t  \t\t\t<li id=\"chatButtonOnNavbar\">\r\n");
      out.write("\t\t          <a href=\"/Housing/src/friends.jsp\"> \r\n");
      out.write("\t\t          <i class=\"glyphicon glyphicon-heart\"> </i> Friends\r\n");
      out.write("\t\t          </a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t<p class=\"navbar-text\">Welcome, ");
      out.print( ((User)(session.getAttribute("curr"))).getFirstName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("          \t\t\t<i class=\"glyphicon glyphicon-user\"></i> <span class=\"caret\"></span></a>\r\n");
      out.write("          \t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("            \t\t\t<li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/profile\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-user\">\r\n");
      out.write("\t\t          \t\t\t</i> My Profile\r\n");
      out.write("\t\t       \t\t\t \t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("\t\t      \t\t\t<li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/top-housing\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-map-marker\">\r\n");
      out.write("\t\t          \t\t\t</i> Top Housing\r\n");
      out.write("\t\t       \t\t\t \t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("\t\t\t            <li class=\"divider\"></li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t\t            \t<a href=\"/Housing/logout\">\r\n");
      out.write("\t\t\t            \t<i class=\"glyphicon glyphicon-off\">\r\n");
      out.write("\t\t          \t\t\t</i> Logout\r\n");
      out.write("\t\t\t            \t</a>\r\n");
      out.write("\t\t\t            </li>\r\n");
      out.write("          \t\t\t</ul>   \r\n");
      out.write("          \t\t</li>   \t\t\t\r\n");
      out.write("          \t</ul>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t ");
} else {
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("          \t\t\t<i class=\"glyphicon glyphicon-user\"></i> <span class=\"caret\"></span></a>\r\n");
      out.write("          \t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("            \t\t\t<li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/login\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-user\">\r\n");
      out.write("\t\t          \t\t\t</i> Login\r\n");
      out.write("\t\t        \t\t\t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("\t\t\t            <li class=\"divider\"></li>\r\n");
      out.write("\t\t\t            <li>\r\n");
      out.write("\t\t        \t\t\t<a href=\"/Housing/signup\"> \r\n");
      out.write("\t\t          \t\t\t<i class=\"glyphicon glyphicon-circle-arrow-up\">\r\n");
      out.write("\t\t          \t\t\t</i> Sign Up\r\n");
      out.write("\t\t        \t\t\t</a>\r\n");
      out.write("\t\t      \t\t\t</li>\r\n");
      out.write("          \t\t\t</ul>   \r\n");
      out.write("          \t\t</li>   \t\t\t\r\n");
      out.write("          \t</ul>\r\n");
      out.write("          \r\n");
      out.write("         ");
} 
      out.write("   \r\n");
      out.write("\t\t \r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- Finished creating the Nav Bar -->\r\n");
      out.write("\r\n");
 
//setting the type for the alert box
String alertType = null;
String alertPhrase = null;
if(request.getAttribute("success") != null && (Boolean)request.getAttribute("success") == true){
	alertType = "alert-success";
	alertPhrase = "Success!";
} else if (request.getAttribute("success") != null && (Boolean)request.getAttribute("success") == false) {
	alertType = "alert-danger";
	alertPhrase = "Error!";
}

      out.write("\r\n");
      out.write("\r\n");
 if(alertType != null){ 
      out.write("\r\n");
      out.write("<div class=\"alert ");
      out.print( alertType );
      out.write(" alert-dismissable fade in\">\r\n");
      out.write("    <span class=\"close\" data-dismiss=\"alert\">&times;</span>\r\n");
      out.write("    <strong>");
      out.print( alertPhrase );
      out.write("</strong> ");
      out.print( request.getAttribute("message") );
      out.write("\r\n");
      out.write("</div>\r\n");
 request.setAttribute("success", null); 
      out.write('\r');
      out.write('\n');
 request.setAttribute("message", null); 
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img src=\"/Housing/lib/images/houSCing.png\" width=\"300px\" height=\"150px\" class=\"img-responsive heading\" alt=\"Housing Logo\"/>\r\n");
      out.write("\r\n");
      out.write("<form class=\"search-form\" method=\"post\" action=\"/Housing/search\">\r\n");
      out.write("\t<input class=\"stretch\" type=\"text\" placeholder=\"Search for Users or Housing\" name=\"keyword\" required/>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<span>Search by: </span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<select name=\"search-type\">\r\n");
      out.write("\t    \t<option value=\"user\" selected=\"selected\">User</option>\r\n");
      out.write("\t    \t<option value=\"housing\">Housing</option> \t\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Search\" class=\"search-button\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- For each return from the query create an html div displaying all information -->\r\n");
 
ResultSet result = (ResultSet)request.getAttribute("queried-result");
String type = (String)request.getAttribute("search-type");
while(result != null && result.next()){
	if(type != null && type.equals("user")){
		ResultSet prefs = (ResultSet)request.getAttribute("user-prefs");
		prefs.next();

      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"info-box\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"info-table\">\r\n");
      out.write("\t  \t\t<tr>\r\n");
      out.write("\t\t\t    <td>\r\n");
      out.write("\t\t\t\t\t<h3>");
      out.print( result.getString("firstName") );
      out.write(' ');
      out.print( result.getString("lastName") );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\tGrade Level: ");
      out.print( prefs.getString("schoolYear") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tPreferred Room Type: ");
      out.print( prefs.getString("preferredRoomType") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tHobbies/Interests: ");
      out.print( prefs.getString("hobbies") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tFun Fact: ");
      out.print( prefs.getString("funFact") );
      out.write("\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t    <td>\r\n");
      out.write("\t\t\t\t\tCook Frequency: ");
      out.print( prefs.getInt("cookFrequency") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tCleanliness ");
      out.print( prefs.getInt("cleanliness") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tParty Frequency: ");
      out.print( prefs.getInt("partyFrequency") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tGuest Frequency: ");
      out.print( prefs.getInt("guestFrequency") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tPreferred Music Level: ");
      out.print( prefs.getInt("musicLoudness") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tStudies in Room: ");
      out.print( prefs.getInt("studyFrequency") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tLevel of Privacy: ");
      out.print( prefs.getInt("privacy") );
      out.write("/10\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tTypical Sleeping Time: ");
      out.print( prefs.getTime("sleepingTime") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tTypical Waking Time: ");
      out.print( prefs.getTime("wakingTime") );
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tPets: ");
if(prefs.getBoolean("pets") == true){ 
      out.write('Y');
      out.write('e');
      out.write('s');
}else{
      out.write('N');
      out.write('o');
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tSmokes: ");
if(prefs.getBoolean("smokes") == true){ 
      out.write('Y');
      out.write('e');
      out.write('s');
}else{
      out.write('N');
      out.write('o');
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\tGreek Life: ");
if(prefs.getBoolean("greek") == true){ 
      out.write('Y');
      out.write('e');
      out.write('s');
}else{
      out.write('N');
      out.write('o');
} 
      out.write("\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t  \t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
		
	} else if (type != null && type.equals("housing")){

      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"info-box\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"info-table\">\r\n");
      out.write("\r\n");
      out.write("\t\t    \t");
 String address= result.getString("address");
		    	address=address.replace(' ', '_');
		    	
      out.write("\r\n");
      out.write("\t\t    \t");
 String img= "lib/images/" +address + ".jpg";
		    	
		    	
      out.write("\r\n");
      out.write("\t\t\t\t<img src=");
      out.print( img );
      out.write(" class=\"searchPic\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"info-table-address\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( result.getString("address") );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li> Distance: ");
      out.print( result.getDouble("distance") );
      out.write(" miles</li>\r\n");
      out.write("\t\t\t\t\t\t<li> Rent: $");
      out.print( result.getInt("rent") );
      out.write("/month</li>\r\n");
      out.write("\t\t\t\t\t\t<li> Minutes from Tommy: ");
      out.print( result.getInt("minutes") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t<li> Number of Beds: ");
      out.print( result.getInt("bed") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t<li> Number of Baths: ");
      out.print( result.getInt("bath") );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t<li> USC Owned: ");
if(result.getInt("uscOwned") == 1){ 
      out.write('Y');
      out.write('E');
      out.write('S');
}else{
      out.write('N');
      out.write('O');
} 
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t<li> Wifi: ");
if(result.getInt("wifi") == 1){ 
      out.write('Y');
      out.write('E');
      out.write('S');
}else{
      out.write('N');
      out.write('O');
} 
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t<li> A/C: ");
if(result.getInt("ac") == 1){ 
      out.write('Y');
      out.write('E');
      out.write('S');
}else{
      out.write('N');
      out.write('O');
} 
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t<li> Parking: ");
if(result.getInt("parking") == 1){ 
      out.write('Y');
      out.write('E');
      out.write('S');
}else{
      out.write('N');
      out.write('O');
} 
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t<li> Cable: ");
if(result.getInt("cable") == 1){ 
      out.write('Y');
      out.write('E');
      out.write('S');
}else{
      out.write('N');
      out.write('O');
} 
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tvar images= document.getElementsByClassName(\"searchPic\");\r\n");
      out.write("\t\r\n");
      out.write("\t\tfor(var aa=0; aa<images.length; aa++)\r\n");
      out.write("\t\t{\t\r\n");
      out.write("\t\t\tvar image= images[aa];\r\n");
      out.write("\t\t\timage.onerror= function(){\r\n");
      out.write("\t\t\t\tthis.src= \"lib/images/genericHouse.jpg\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<div ");
 if(session.getAttribute("curr") == null){ 
      out.write(" class=\"parent-div invisible\" ");
} 
      out.write(" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form id=\"save-form\" class=\"inline-form\" action=\"/Housing/save-housing\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"invisible\" name=\"housingID\" value=");
      out.print( "" + result.getInt("keyid") );
      out.write(" />\r\n");
      out.write("\t\t<input type=\"submit\" class=\"form-button\" value=\"Save\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form id=\"review-form\" class=\"inline-form\" action=\"/Housing/review-housing\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"invisible\" name=\"housingID\" value=");
      out.print( "" + result.getInt("keyid") );
      out.write(" />\r\n");
      out.write("\t\t<input type=\"submit\" class=\"form-button\" value=\"Review\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
		
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
